insert into public.exercises (name, muscle_group) values
  ('Press banca', 'upper'),
  ('Press banca inclinado', 'upper'),
  ('Press banca con mancuernas', 'upper'),
  ('Press militar', 'upper'),
  ('Press militar con mancuernas', 'upper'),
  ('Press Arnold', 'upper'),
  ('Fondos en paralelas', 'upper'),
  ('Fondos de tríceps', 'upper'),
  ('Flexiones de brazos', 'upper'),
  ('Dominadas', 'upper'),
  ('Dominadas supinas', 'upper'),
  ('Remo con barra', 'upper'),
  ('Remo con mancuerna', 'upper'),
  ('Remo en polea baja', 'upper'),
  ('Remo en máquina', 'upper'),
  ('Jalón al pecho', 'upper'),
  ('Jalón tras nuca', 'upper'),
  ('Elevaciones laterales', 'upper'),
  ('Elevaciones frontales', 'upper'),
  ('Pájaros (deltoide posterior)', 'upper'),
  ('Curl de bíceps con barra', 'upper'),
  ('Curl de bíceps con mancuernas', 'upper'),
  ('Curl martillo', 'upper'),
  ('Curl en banco scott', 'upper'),
  ('Extensión de tríceps en polea', 'upper'),
  ('Extensión de tríceps sobre la cabeza', 'upper'),
  ('Press francés', 'upper'),
  ('Aperturas con mancuernas', 'upper'),
  ('Cruces en polea', 'upper'),
  ('Face pull', 'upper'),
  ('Encogimientos de hombros', 'upper'),
  ('Sentadilla con barra', 'lower'),
  ('Sentadilla frontal', 'lower'),
  ('Sentadilla búlgara', 'lower'),
  ('Sentadilla goblet', 'lower'),
  ('Peso muerto', 'lower'),
  ('Peso muerto rumano', 'lower'),
  ('Peso muerto sumo', 'lower'),
  ('Prensa de piernas', 'lower'),
  ('Zancadas', 'lower'),
  ('Zancadas con mancuernas', 'lower'),
  ('Curl femoral en máquina', 'lower'),
  ('Extensión de cuádriceps en máquina', 'lower'),
  ('Hip thrust', 'lower'),
  ('Puente de glúteos', 'lower'),
  ('Elevación de talones (gemelos de pie)', 'lower'),
  ('Elevación de talones sentado', 'lower'),
  ('Abducción de cadera en máquina', 'lower'),
  ('Aducción de cadera en máquina', 'lower'),
  ('Plancha abdominal', 'core'),
  ('Plancha lateral', 'core'),
  ('Crunch abdominal', 'core'),
  ('Elevación de piernas colgado', 'core'),
  ('Rueda abdominal', 'core'),
  ('Giro ruso', 'core'),
  ('Hollow hold', 'core')
on conflict (name) do nothing;
